### ISSUE TITLE
Error in reading Soil Parameter File

### ISSUE THREAD

**Issue by LSRathore** [jhamman/VIC_glacier#1]
I am trying to run the glacier module over my area, I have frozen soil off and full energy true in global parameter file.  
It gives the following error while running:
`ERROR: Can't find values for GLACIER CELL NUMBER in soil file`
What parameter should be added new in the soil parameter file to run this?

**Comment by jhamman** [comment]
I recommend emailing the vic_users forum (https://mailman13.u.washington.edu/mailman/listinfo/vic_users) to see if anyone can help you. This repository is no longer maintained.
